---
name: Terraform Destroy
on:
  workflow_dispatch: null
jobs:
  tf-destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show Destroy plan
        run: terraform plan -destroy
        continue-on-error: true
      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve

